if (location.search || location.hash) history.replaceState(null, '', location.pathname);

const captures = [
  {id:'c1',date:'01 Sep 2026',progress:42,images:278},
  {id:'c2',date:'10 Sep 2026',progress:51,images:294},
  {id:'c3',date:'17 Sep 2026',progress:58,images:306},
  {id:'c4',date:'23 Sep 2026',progress:68.2,images:312}
];

const titles={
  dashboard:['Executive Overview','A private spatial record of construction progress, change and quality.'],
  viewer:['3D Site Viewer','Inspect a dated spatial state and create coordinate-linked observations.'],
  compare:['Time Comparison','Compare the same construction location across capture dates.'],
  capture:['Capture Ingestion','Select drone imagery and prepare a controlled reconstruction job.'],
  processing:['Private Reconstruction','Demonstrate the private images-to-spatial-state workflow.'],
  quality:['Quality Intelligence','Prioritise spatial observations for authorised human verification.'],
  roadmap:['Project Roadmap','Move from proof of concept to a controlled production platform.'],
  inspections:['Inspection Register','Maintain a traceable record of coordinate-linked observations.'],
  report:['Management Report','Translate spatial change into a management-ready evidence summary.'],
  architecture:['Technical Boundary','Separate the browser proof of concept from secure production services.']
};

function showView(id){
  document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));
  document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));
  const t=titles[id]||titles.dashboard;
  document.getElementById('pageTitle').textContent=t[0];
  document.getElementById('pageSubtitle').textContent=t[1];
  window.scrollTo({top:0,behavior:'smooth'});
  if(id==='viewer') requestAnimationFrame(renderSite);
  if(id==='compare') requestAnimationFrame(renderCompare);
}

document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.goto)));

const mini=document.getElementById('miniTimeline');
captures.slice().reverse().forEach(c=>mini.insertAdjacentHTML('beforeend',`<div class="mini-timeline-item"><div><b>${c.date}</b><div class="muted">${c.images} images</div></div><strong>${c.progress}%</strong></div>`));
const timeline=document.getElementById('captureTimeline');
captures.forEach(c=>timeline.insertAdjacentHTML('beforeend',`<div class="timeline-node ${c.id==='c4'?'active':''}"><b>${c.date}</b><small>${c.images} images · ${c.progress}% demo progress</small></div>`));

const dateA=document.getElementById('dateASelect'),dateB=document.getElementById('dateBSelect'),viewerDate=document.getElementById('viewerDateSelect');
captures.forEach(c=>[dateA,dateB,viewerDate].forEach(s=>s.add(new Option(`${c.date} · ${c.progress}%`,c.id))));
dateA.value='c1'; dateB.value='c4'; viewerDate.value='c4';

const extra=document.createElement('style');
extra.textContent=`
.virtual-3d{position:absolute;inset:0;overflow:hidden;perspective:950px;background:linear-gradient(180deg,#dce8ef 0%,#edf2f5 54%,#d1d8d3 54%,#c5cec7 100%)}
.site-stage{position:absolute;left:50%;top:52%;width:760px;height:520px;transform-style:preserve-3d;transform:translate(-50%,-50%) rotateX(58deg) rotateZ(-28deg) scale(.84);transition:transform .12s ease-out}
.site-ground{position:absolute;inset:0;background-color:#c8d1cb;background-image:linear-gradient(rgba(70,90,105,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(70,90,105,.14) 1px,transparent 1px);background-size:32px 32px;border:1px solid rgba(70,90,105,.35);box-shadow:0 22px 60px rgba(20,35,45,.25);transform-style:preserve-3d}
.site-road{position:absolute;background:#9fa9aa;border:1px solid rgba(255,255,255,.35)}
.site-road.r1{left:0;right:0;top:160px;height:42px}.site-road.r2{top:0;bottom:0;left:500px;width:48px}
.building{position:absolute;transform-style:preserve-3d;filter:drop-shadow(6px 8px 5px rgba(20,30,40,.23))}.building .top{position:absolute;inset:0;background:#4a7194;border:1px solid rgba(255,255,255,.35)}.building .front,.building .side{position:absolute;background:#365d7e;border:1px solid rgba(255,255,255,.17)}.building .front{left:0;right:0;height:var(--h);top:100%;transform-origin:top;transform:rotateX(-90deg)}.building .side{top:0;bottom:0;width:var(--h);left:100%;transform-origin:left;transform:rotateY(90deg)}
.pin3d{position:absolute;width:17px;height:17px;border-radius:50%;background:#b43e3e;border:3px solid white;box-shadow:0 4px 12px rgba(0,0,0,.3);transform:translate(-50%,-50%);z-index:20}.viewer-help{position:absolute;right:14px;bottom:14px;background:rgba(13,24,34,.82);color:white;padding:8px 10px;border-radius:8px;font-size:11px;z-index:25}
.compare-layer{position:absolute;inset:0;transition:opacity .15s}.compare-early .building .top{background:#d09b4d}.compare-early .building .front,.compare-early .building .side{background:#bb8130}.compare-late .building .top{background:#3e6688}.compare-late .building .front,.compare-late .building .side{background:#31536f}
.preview-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:14px}.preview-card{height:92px;border-radius:10px;overflow:hidden;border:1px solid #dde4e9;background:#f3f6f8;position:relative}.preview-card img{width:100%;height:100%;object-fit:cover}.preview-card span{position:absolute;left:6px;right:6px;bottom:5px;background:rgba(10,20,30,.72);color:#fff;padding:3px 5px;border-radius:5px;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.value-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.value-grid div{padding:14px;border:1px solid #e1e6eb;border-radius:12px;background:#f8fafb}.value-grid b{display:block;font-size:12px}.value-grid span{display:block;color:#6f7b88;font-size:10px;line-height:1.5;margin-top:5px}
.roadmap{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-top:16px}.road-phase{padding:14px;border:1px solid #e0e6eb;border-radius:11px;background:#f7f9fb;min-height:105px}.road-phase b,.road-phase span,.road-phase small{display:block}.road-phase b{font-size:10px;color:#9b6d2f}.road-phase span{font-size:12px;font-weight:800;margin-top:5px}.road-phase small{font-size:10px;color:#76828f;margin-top:7px}.road-phase.done{background:#edf7f2;border-color:#cce4d8}.road-phase.active{background:#fff6e7;border-color:#dfc392}
@media(max-width:1000px){.value-grid,.roadmap{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.preview-grid,.value-grid,.roadmap{grid-template-columns:1fr 1fr}}
`;
document.head.appendChild(extra);

const blocks=[
  {x:48,y:55,w:108,d:76,max:62},{x:188,y:55,w:108,d:76,max:90},{x:328,y:55,w:108,d:76,max:112},
  {x:48,y:230,w:108,d:76,max:98},{x:188,y:230,w:108,d:76,max:128},{x:328,y:230,w:108,d:76,max:78},
  {x:92,y:382,w:148,d:66,max:58},{x:286,y:382,w:166,d:66,max:92},{x:570,y:72,w:105,d:85,max:72},{x:570,y:260,w:105,d:85,max:105}
];
let rotX=58,rotZ=-28,scale=.84,drag=false,lastX=0,lastY=0,gridVisible=true,markersVisible=true,markerPoint=null,selected={x:0,y:0,z:0};
function buildingHTML(b,i,progress){const f=Math.max(.16,Math.min(1,progress/100+((i%3)-1)*.11)),h=Math.round(b.max*f);return `<div class="building" style="left:${b.x}px;top:${b.y}px;width:${b.w}px;height:${b.d}px;--h:${h}px"><div class="top"></div><div class="front"></div><div class="side"></div></div>`}
function transform(){return `translate(-50%,-50%) rotateX(${rotX}deg) rotateZ(${rotZ}deg) scale(${scale})`}
function attachInteraction(host,stage){host.onpointerdown=e=>{if(e.target.closest('button,select,textarea,input'))return;drag=true;lastX=e.clientX;lastY=e.clientY;host.setPointerCapture?.(e.pointerId)};host.onpointermove=e=>{if(!drag)return;rotZ+=(e.clientX-lastX)*.24;rotX=Math.max(34,Math.min(76,rotX-(e.clientY-lastY)*.18));lastX=e.clientX;lastY=e.clientY;stage.style.transform=transform()};host.onpointerup=()=>drag=false;host.onpointercancel=()=>drag=false;host.onwheel=e=>{e.preventDefault();scale=Math.max(.52,Math.min(1.3,scale-e.deltaY*.0008));stage.style.transform=transform()}}
function makeGround(){const g=document.createElement('div');g.className='site-ground';if(!gridVisible)g.style.backgroundImage='none';g.insertAdjacentHTML('beforeend','<div class="site-road r1"></div><div class="site-road r2"></div>');return g}
function renderSite(){const host=document.getElementById('threeViewer');if(!host)return;const c=captures.find(x=>x.id===viewerDate.value)||captures[3];document.getElementById('viewerDateLabel').textContent=c.date;host.querySelectorAll('.virtual-3d').forEach(n=>n.remove());const shell=document.createElement('div');shell.className='virtual-3d';const stage=document.createElement('div');stage.className='site-stage';stage.style.transform=transform();const ground=makeGround();blocks.forEach((b,i)=>ground.insertAdjacentHTML('beforeend',buildingHTML(b,i,c.progress)));if(markerPoint&&markersVisible){const p=document.createElement('div');p.className='pin3d';p.style.left=markerPoint.left+'px';p.style.top=markerPoint.top+'px';ground.appendChild(p)}stage.appendChild(ground);shell.appendChild(stage);shell.insertAdjacentHTML('beforeend','<div class="viewer-help">Drag to rotate · Scroll to zoom · Click site to inspect</div>');host.appendChild(shell);attachInteraction(shell,stage);shell.addEventListener('click',e=>{if(drag)return;const r=ground.getBoundingClientRect();const cx=Math.max(0,Math.min(760,e.clientX-r.left)),cy=Math.max(0,Math.min(520,e.clientY-r.top));markerPoint={left:cx,top:cy};selected={x:(cx-380)/10,y:0,z:(260-cy)/10};document.getElementById('coordX').textContent=selected.x.toFixed(2)+' m';document.getElementById('coordZ').textContent=selected.z.toFixed(2)+' m';document.getElementById('coordY').textContent='0.00 m';document.getElementById('coordsOverlay').textContent=`X ${selected.x.toFixed(2)} · Y 0.00 · Z ${selected.z.toFixed(2)}`;renderSite()})}

function renderCompare(){const host=document.getElementById('compareViewer');if(!host)return;const a=captures.find(x=>x.id===dateA.value),b=captures.find(x=>x.id===dateB.value);host.querySelectorAll('.virtual-3d').forEach(n=>n.remove());const shell=document.createElement('div');shell.className='virtual-3d';const stage=document.createElement('div');stage.className='site-stage';stage.style.transform=transform();const ground=makeGround();const early=document.createElement('div');early.className='compare-layer compare-early';const late=document.createElement('div');late.className='compare-layer compare-late';blocks.forEach((bl,i)=>{early.insertAdjacentHTML('beforeend',buildingHTML(bl,i,a.progress));late.insertAdjacentHTML('beforeend',buildingHTML(bl,i,b.progress))});ground.append(early,late);stage.appendChild(ground);shell.appendChild(stage);host.appendChild(shell);attachInteraction(shell,stage);applyBlend()}
function applyBlend(){const v=(+document.getElementById('blendSlider').value)/100;document.querySelectorAll('.compare-late').forEach(x=>x.style.opacity=Math.max(.2,v));document.querySelectorAll('.compare-early').forEach(x=>x.style.opacity=Math.max(.2,1-v+.2))}
function renderChanges(){const a=captures.find(x=>x.id===dateA.value),b=captures.find(x=>x.id===dateB.value),delta=(b.progress-a.progress).toFixed(1);document.getElementById('blendALabel').textContent=a.date;document.getElementById('blendBLabel').textContent=b.date;document.getElementById('changeCards').innerHTML=`<article class="panel compact"><span class="kicker">Overall change</span><h3>Progress delta</h3><div class="big-value positive">${delta>0?'+':''}${delta}%</div><p>Demonstration indicator across selected states.</p></article><article class="panel compact"><span class="kicker">Geometry</span><h3>Changed zones</h3><div class="big-value">6</div><p>Zones with material geometric difference.</p></article><article class="panel compact"><span class="kicker">Review</span><h3>Human verification</h3><div class="big-value warning">4</div><p>Observations requiring authorised review.</p></article>`;renderCompare()}
dateA.addEventListener('change',renderChanges);dateB.addEventListener('change',renderChanges);viewerDate.addEventListener('change',renderSite);document.getElementById('blendSlider').addEventListener('input',applyBlend);document.getElementById('resetCamera').addEventListener('click',()=>{rotX=58;rotZ=-28;scale=.84;renderSite()});document.getElementById('toggleGrid').addEventListener('click',()=>{gridVisible=!gridVisible;renderSite()});document.getElementById('toggleMarkers').addEventListener('click',()=>{markersVisible=!markersVisible;renderSite()});
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.compare-early .building').forEach(x=>x.style.filter=b.dataset.mode==='difference'?'saturate(1.5) brightness(1.05)':'');document.querySelectorAll('.compare-late .building').forEach(x=>x.style.filter=b.dataset.mode==='difference'?'saturate(1.5) contrast(1.1)':'')}));

const inspections=[{id:'INSP-014',date:'23 Sep 2026',coord:'E 18.4 · N 27.6',note:'Verify wall alignment at northern return.',status:'Open'},{id:'INSP-013',date:'17 Sep 2026',coord:'E -6.2 · N 15.1',note:'Roof progress confirmed against prior capture.',status:'Closed'}];
function renderInspections(){const body=document.querySelector('#inspectionTable tbody');body.innerHTML='';inspections.forEach(i=>body.insertAdjacentHTML('beforeend',`<tr><td>${i.id}</td><td>${i.date}</td><td>${i.coord}</td><td>${i.note}</td><td><span class="pill ${i.status==='Closed'?'good':'neutral'}">${i.status}</span></td></tr>`))}
document.getElementById('saveMarker').addEventListener('click',()=>{const note=document.getElementById('inspectionNote').value.trim()||'Spatial inspection marker';inspections.unshift({id:'INSP-'+String(inspections.length+15).padStart(3,'0'),date:captures.find(c=>c.id===viewerDate.value).date,coord:`E ${selected.x.toFixed(1)} · N ${selected.z.toFixed(1)}`,note,status:'Open'});renderInspections();document.getElementById('inspectionNote').value='';alert('Inspection marker saved to the demonstration register.')});renderInspections();

const quality=[{title:'Wall progress variance',priority:'Medium',coord:'Grid E 18.4 m · N 27.6 m',desc:'Observed geometry appears behind the expected state for this zone. Human verification is required.'},{title:'Surface variation',priority:'Medium',coord:'Grid E -21.1 m · N 14.8 m',desc:'A localised surface difference is visible in the comparison. Verify whether it is temporary material, site condition or model noise.'},{title:'Service corridor unchanged',priority:'Low',coord:'Grid E 2.8 m · N -18.9 m',desc:'Limited geometric change is visible between the selected dates. Compare against programme before escalation.'},{title:'Roof sequence visible',priority:'Low',coord:'Grid E 11.0 m · N 2.0 m',desc:'Later spatial state shows roof geometry absent from the baseline. Record as progress after human review.'}];
const ql=document.getElementById('qualityList');quality.forEach((q,i)=>{const el=document.createElement('div');el.className='quality-item'+(i===0?' active':'');el.innerHTML=`<div class="quality-item-head"><strong>${q.title}</strong><span class="priority">${q.priority}</span></div><p>${q.coord}</p>`;el.addEventListener('click',()=>{document.querySelectorAll('.quality-item').forEach(x=>x.classList.remove('active'));el.classList.add('active');document.getElementById('qualityTitle').textContent=q.title;document.getElementById('qualityPriority').textContent=q.priority;document.getElementById('qualityDescription').textContent=q.desc;document.getElementById('qualityCoord').textContent=q.coord});ql.appendChild(el)});

const fileInput=document.getElementById('captureFiles'),upload=document.getElementById('uploadZone'),preview=document.getElementById('imagePreviewGrid');
function updateManifest(list){const files=[...list],size=files.reduce((s,f)=>s+f.size,0);document.getElementById('captureManifestTitle').textContent=files.length?`Selected capture · ${files.length} image${files.length===1?'':'s'}`:'No capture selected';document.getElementById('manifestCount').textContent=files.length||'—';document.getElementById('manifestSize').textContent=files.length?(size/1024/1024).toFixed(1)+' MB':'—';document.getElementById('manifestGps').textContent=files.length?'Pending private extraction':'—';document.getElementById('manifestTime').textContent=files[0]?new Date(files[0].lastModified).toLocaleString():'—';document.getElementById('manifestAltitude').textContent=files.length?'Pending metadata':'—';document.getElementById('manifestOverlap').textContent=files.length?'Pending validation':'—';preview.innerHTML='';files.slice(0,8).forEach(f=>{const card=document.createElement('div');card.className='preview-card';const img=document.createElement('img');img.src=URL.createObjectURL(f);img.onload=()=>URL.revokeObjectURL(img.src);const cap=document.createElement('span');cap.textContent=f.name;card.append(img,cap);preview.appendChild(card)});if(files.length>8)preview.insertAdjacentHTML('beforeend',`<div class="preview-card" style="display:grid;place-items:center;font-size:12px;font-weight:800">+${files.length-8} more</div>`)}
fileInput.addEventListener('change',()=>updateManifest(fileInput.files));upload.addEventListener('click',e=>{if(e.target!==fileInput)fileInput.click()});['dragenter','dragover'].forEach(ev=>upload.addEventListener(ev,e=>{e.preventDefault();upload.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>upload.addEventListener(ev,e=>{e.preventDefault();upload.classList.remove('dragging')}));upload.addEventListener('drop',e=>updateManifest(e.dataTransfer.files));
document.getElementById('loadDemoCapture').addEventListener('click',()=>{document.getElementById('captureManifestTitle').textContent='CentralBlue Demonstration Capture · 23 Sep 2026';document.getElementById('manifestCount').textContent='312';document.getElementById('manifestSize').textContent='4.6 GB';document.getElementById('manifestGps').textContent='312 / 312';document.getElementById('manifestTime').textContent='09:14–09:37';document.getElementById('manifestAltitude').textContent='62 m AGL';document.getElementById('manifestOverlap').textContent='Ready';preview.innerHTML='<div class="preview-card" style="display:grid;place-items:center;font-size:11px">Demo image set</div><div class="preview-card" style="display:grid;place-items:center;font-size:11px">Geotags verified</div><div class="preview-card" style="display:grid;place-items:center;font-size:11px">Overlap checked</div><div class="preview-card" style="display:grid;place-items:center;font-size:11px">Ready to process</div>'});

const stages=['Images validated','Feature alignment','Spatial point model','Surface model','Coordinate alignment','Spatial state ready'];const pipeline=document.getElementById('pipelineSteps');stages.forEach((s,i)=>pipeline.insertAdjacentHTML('beforeend',`<div class="pipeline-step"><b>${String(i+1).padStart(2,'0')} · ${s}</b><span>Waiting</span></div>`));document.getElementById('runPipeline').addEventListener('click',async()=>{const els=[...document.querySelectorAll('.pipeline-step')];els.forEach(e=>{e.className='pipeline-step';e.querySelector('span').textContent='Waiting'});for(const e of els){e.classList.add('running');e.querySelector('span').textContent='Processing…';await new Promise(r=>setTimeout(r,520));e.classList.remove('running');e.classList.add('done');e.querySelector('span').textContent='Complete'}});

renderChanges();renderSite();
