/* Synthetic, single-browser workflow demo. No real identities, uploads or approvals. */
(() => {
'use strict';
const KEY='citra_workflow_demo_v1';
const initial=()=>({suppliers:[],opportunities:[],bids:[],contracts:[],events:[]});
let state;
try { state=JSON.parse(localStorage.getItem(KEY))||initial(); } catch { state=initial(); }
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
const now=()=>new Date().toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'});
function log(action,ref){state.events.unshift({at:now(),action,ref});state.events=state.events.slice(0,100)}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function notice(msg,bad=false){const n=$('wfNotice');n.textContent=msg;n.className='notice '+(bad?'red':'green');n.hidden=false;n.scrollIntoView({block:'nearest',behavior:'smooth'})}
function selected(id){return $(id).value}
function required(value,label){if(!String(value||'').trim())throw Error(`${label} is required.`);return String(value).trim()}
function supplier(id){return state.suppliers.find(s=>s.id===id)}
function opp(id){return state.opportunities.find(o=>o.id===id)}
function bid(id){return state.bids.find(b=>b.id===id)}
function files(input){return [...input.files].map(f=>{if(f.size>10*1024*1024)throw Error(`${f.name} exceeds 10 MB.`);if(!/\.(pdf|png|jpe?g|webp)$/i.test(f.name))throw Error('Use PDF, PNG, JPG or WebP files.');return {name:f.name,size:f.size,type:f.type}})}
function option(value,label){return `<option value="${esc(value)}">${esc(label)}</option>`}
function setOptions(id,items,label){const el=$(id), prior=el.value;el.innerHTML=option('',label)+items.map(x=>option(x.id,x.label)).join('');if(items.some(x=>x.id===prior))el.value=prior}
const nav=$('nav');const entry=document.createElement('button');entry.dataset.section='workflow';entry.textContent='Working Lifecycle Demo';nav.insertBefore(entry,nav.children[1]);
const section=document.createElement('section');section.id='workflow';section.className='section';section.innerHTML=`
<div class="card panel"><h3>Working lifecycle · synthetic data</h3><p class="lead">Try registration, document review, opportunity, bid, decision and contract progress in this browser. Records and file names stay in this browser only. Files are selected for demonstration but their contents are not uploaded or saved. Do not enter real personal, banking, pricing or contractor information.</p><div id="wfNotice" class="notice green" hidden></div><div class="actions"><button class="btn ghost" id="wfSeed" type="button">Load sample journey</button><button class="btn danger" id="wfReset" type="button">Clear browser demo</button></div></div>
<div class="split"><div class="card panel"><h3>1 · Contractor registration</h3><form id="wfSupplierForm"><div class="field"><label for="wfName">Company name</label><input id="wfName" required placeholder="Sample Tiling Co" maxlength="100"></div><div class="three"><div class="field"><label for="wfCsd">CSD reference (sample)</label><input id="wfCsd" required placeholder="MAAA0000000" maxlength="40"></div><div class="field"><label for="wfCategory">Work category</label><select id="wfCategory"><option>Tiling</option><option>Electrical</option><option>Plumbing</option><option>Security</option><option>Construction</option><option>Other</option></select></div><div class="field"><label for="wfArea">Sourcing area</label><select id="wfArea"><option>Blue Downs</option><option>Cape Town</option><option>Western Cape</option><option>South Africa</option></select></div></div><div class="field"><label for="wfDoc">Sample compliance document (PDF/image, up to 10 MB)</label><input id="wfDoc" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" required></div><button class="btn gold">Register and submit for review</button></form></div><div class="card panel"><h3>2 · Review queue</h3><div class="field"><label for="wfReviewSupplier">Contractor</label><select id="wfReviewSupplier"></select></div><div class="field"><label for="wfReviewReason">Reviewer reason / correction instruction</label><textarea id="wfReviewReason" placeholder="State the evidence reviewed or exact correction required"></textarea></div><div class="actions"><button class="btn primary" id="wfApprove" type="button">Approve</button><button class="btn ghost" id="wfReturn" type="button">Return for correction</button><button class="btn danger" id="wfReject" type="button">Reject</button></div><div class="field" style="margin-top:16px"><label for="wfReplace">Replacement document for returned application</label><input id="wfReplace" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp"></div><button class="btn ghost" id="wfResubmit" type="button">Resubmit correction</button></div></div>
<div class="split"><div class="card panel"><h3>3 · Publish an opportunity</h3><form id="wfOpportunityForm"><div class="field"><label for="wfTitle">Scope / title</label><input id="wfTitle" required maxlength="120" placeholder="Tiling for Phase 21"></div><div class="three"><div class="field"><label for="wfMethod">Method</label><select id="wfMethod"><option>RFI</option><option>RFQ</option><option>RFP</option><option>Tender</option></select></div><div class="field"><label for="wfOppCategory">Category</label><select id="wfOppCategory"><option>Tiling</option><option>Electrical</option><option>Plumbing</option><option>Security</option><option>Construction</option><option>Other</option></select></div><div class="field"><label for="wfClose">Closing date/time</label><input id="wfClose" type="datetime-local" required></div></div><div class="field"><label for="wfScope">Scope summary</label><textarea id="wfScope" required></textarea></div><button class="btn gold">Publish sample opportunity</button></form><div class="actions" style="margin-top:14px"><button class="btn ghost" id="wfCloseSample" type="button">Close selected sample opportunity now</button></div></div><div class="card panel"><h3>4 · Supplier submission</h3><div class="field"><label for="wfBidSupplier">Approved contractor</label><select id="wfBidSupplier"></select></div><div class="field"><label for="wfBidOpportunity">Matching opportunity</label><select id="wfBidOpportunity"></select></div><div class="field"><label for="wfBidFile">Sample bid document (PDF/image, up to 10 MB)</label><input id="wfBidFile" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp"></div><div class="field"><label><input id="wfSign" type="checkbox"> I confirm this sample submission is authorised</label></div><div class="actions"><button class="btn gold" id="wfBid" type="button">Submit sample bid</button><button class="btn ghost" id="wfWithdraw" type="button">Withdraw selected bid</button></div><div id="wfReceipt" class="notice green" hidden style="margin-top:12px"></div></div></div>
<div class="split"><div class="card panel"><h3>5 · Evaluation and decision</h3><div class="field"><label for="wfEvalBid">Submission</label><select id="wfEvalBid"></select></div><div class="field"><label for="wfDecisionReason">Decision reason</label><textarea id="wfDecisionReason" placeholder="Record the assessment and reasons"></textarea></div><div class="actions"><button class="btn primary" id="wfAward" type="button">Record award</button><button class="btn ghost" id="wfClarify" type="button">Request clarification</button><button class="btn danger" id="wfDecline" type="button">Record unsuccessful outcome</button></div></div><div class="card panel"><h3>6 · Contract progress</h3><div class="field"><label for="wfContract">Awarded contract</label><select id="wfContract"></select></div><div class="field"><label for="wfProgress">Next stage</label><select id="wfProgress"><option>Contract signed</option><option>Delivery in progress</option><option>Work verified</option><option>Invoice reviewed</option><option>Closed out</option></select></div><div class="field"><label for="wfProgressNote">Progress note</label><textarea id="wfProgressNote" placeholder="Describe supporting evidence or outstanding action"></textarea></div><button class="btn gold" id="wfAdvance" type="button">Record stage</button></div></div>
<div class="card panel"><h3>Live sample records</h3><div id="wfTables"></div></div><div class="card panel"><h3>Activity history in this browser</h3><div id="wfEvents"></div></div>`;
document.querySelector('.footer-note').before(section);
const titlesMap={...titles,workflow:'Working Lifecycle Demo'};
entry.addEventListener('click',()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));entry.classList.add('active');document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));section.classList.add('active');$('pageTitle').textContent=titlesMap.workflow;window.scrollTo(0,0)});
function render(){
 setOptions('wfReviewSupplier',state.suppliers.map(s=>({id:s.id,label:`${s.name} · ${s.status}`})),'Choose contractor');
 setOptions('wfBidSupplier',state.suppliers.filter(s=>s.status==='Approved').map(s=>({id:s.id,label:s.name})),'Choose approved contractor');
 updateBidOpportunities();
 setOptions('wfEvalBid',state.bids.filter(b=>b.status!=='Withdrawn').map(b=>({id:b.id,label:`${b.id} · ${supplier(b.supplierId)?.name||'Unknown'} · ${b.status}`})),'Choose submission');
 setOptions('wfContract',state.contracts.map(c=>({id:c.id,label:`${c.id} · ${supplier(c.supplierId)?.name||'Unknown'} · ${c.stage}`})),'Choose contract');
 const status=s=>`<span class="pill ${s==='Approved'||s==='Awarded'||s==='Closed out'?'ok':s==='Rejected'||s==='Unsuccessful'?'bad':'warn'}">${esc(s)}</span>`;
 $('wfTables').innerHTML=`<div class="wf-scroll"><h4>Contractors</h4><table><thead><tr><th>Ref</th><th>Contractor</th><th>Category / area</th><th>Document</th><th>Status</th><th>Reason</th></tr></thead><tbody>${state.suppliers.map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.name)}</td><td>${esc(s.category)} · ${esc(s.area)}</td><td>${esc(s.doc?.name)} · v${s.version}</td><td>${status(s.status)}</td><td>${esc(s.reason||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No sample contractors yet.</td></tr>'}</tbody></table><h4>Opportunities and submissions</h4><table><thead><tr><th>Ref</th><th>Opportunity</th><th>Category</th><th>Closing</th><th>Submissions</th></tr></thead><tbody>${state.opportunities.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.title)}</td><td>${esc(o.category)}</td><td>${esc(o.close.replace('T',' '))}</td><td>${state.bids.filter(b=>b.opportunityId===o.id).length}</td></tr>`).join('')||'<tr><td colspan="5">No sample opportunities yet.</td></tr>'}</tbody></table><h4>Bid and contract tracker</h4><table><thead><tr><th>Receipt</th><th>Contractor</th><th>Opportunity</th><th>Bid status</th><th>Contract stage</th></tr></thead><tbody>${state.bids.map(b=>`<tr><td>${esc(b.id)}</td><td>${esc(supplier(b.supplierId)?.name)}</td><td>${esc(opp(b.opportunityId)?.title)}</td><td>${status(b.status)}${b.reason?' · '+esc(b.reason):''}</td><td>${esc(state.contracts.find(c=>c.bidId===b.id)?.stage||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No sample submissions yet.</td></tr>'}</tbody></table></div>`;
 $('wfEvents').innerHTML=state.events.length?`<div class="wf-scroll"><table><thead><tr><th>Time</th><th>Record</th><th>Action</th></tr></thead><tbody>${state.events.map(e=>`<tr><td>${esc(e.at)}</td><td>${esc(e.ref)}</td><td>${esc(e.action)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="lead">No actions recorded.</p>';
}
function updateBidOpportunities(){const s=supplier(selected('wfBidSupplier'));setOptions('wfBidOpportunity',state.opportunities.filter(o=>s&&o.category===s.category&&new Date(o.close)>new Date()).map(o=>({id:o.id,label:`${o.id} · ${o.title}`})),'Choose open matching opportunity')}
$('wfBidSupplier').addEventListener('change',updateBidOpportunities);
function run(fn){try{fn()}catch(e){notice(e.message,true)}}
$('wfSupplierForm').addEventListener('submit',e=>{e.preventDefault();run(()=>{const doc=files($('wfDoc'))[0];if(!doc)throw Error('Choose a sample compliance document.');const s={id:uid('SUP'),name:required(selected('wfName'),'Company name'),csd:required(selected('wfCsd'),'CSD reference'),category:selected('wfCategory'),area:selected('wfArea'),doc,version:1,status:'Awaiting review',reason:''};state.suppliers.push(s);log('Registration submitted with document name; CSD not externally verified',s.id);save();e.target.reset();notice(`${s.id} submitted for sample review.`)})});
function review(status){run(()=>{const s=supplier(selected('wfReviewSupplier'));if(!s)throw Error('Choose a contractor.');if(s.status!=='Awaiting review')throw Error('Only submitted applications can be reviewed; returned applications require resubmission.');const reason=required(selected('wfReviewReason'),'Reviewer reason');if(reason.length<12)throw Error('Provide a meaningful reviewer reason (at least 12 characters).');s.status=status;s.reason=reason;log(`${status}: ${reason}`,s.id);save();notice(`${s.id}: ${status}.`)})}
$('wfApprove').onclick=()=>review('Approved');$('wfReturn').onclick=()=>review('Returned for correction');$('wfReject').onclick=()=>review('Rejected');
$('wfResubmit').onclick=()=>run(()=>{const s=supplier(selected('wfReviewSupplier'));if(!s||s.status!=='Returned for correction')throw Error('Choose a returned application.');const doc=files($('wfReplace'))[0];if(!doc)throw Error('Select a replacement file.');s.doc=doc;s.version++;s.status='Awaiting review';s.reason='';log(`Replacement document selected (v${s.version}); review requested`,s.id);save();$('wfReplace').value='';notice(`${s.id} resubmitted.`)});
$('wfOpportunityForm').addEventListener('submit',e=>{e.preventDefault();run(()=>{const close=selected('wfClose');if(new Date(close)<=new Date())throw Error('Closing must be in the future.');const o={id:uid(selected('wfMethod')),method:selected('wfMethod'),title:required(selected('wfTitle'),'Title'),category:selected('wfOppCategory'),close,scope:required(selected('wfScope'),'Scope summary')};state.opportunities.push(o);log('Sample opportunity published',o.id);save();e.target.reset();notice(`${o.id} published in this browser.`)})});
$('wfCloseSample').onclick=()=>run(()=>{const o=opp(selected('wfBidOpportunity'));if(!o)throw Error('Choose a sample opportunity in the submission panel.');if(!state.bids.some(b=>b.opportunityId===o.id&&b.status==='Submitted'))throw Error('Submit a sample bid before closing this opportunity.');o.close=new Date(Date.now()-60000).toISOString();log('Sample closing simulated',o.id);save();notice(`${o.id} closed for the demo. Its bid can now be evaluated.`)});
$('wfBid').onclick=()=>run(()=>{const s=supplier(selected('wfBidSupplier')),o=opp(selected('wfBidOpportunity'));if(!s||s.status!=='Approved'||!o||o.category!==s.category)throw Error('Choose an approved, matching contractor and opportunity.');if(new Date(o.close)<=new Date())throw Error('The opportunity has closed.');if(state.bids.some(b=>b.supplierId===s.id&&b.opportunityId===o.id&&b.status!=='Withdrawn'))throw Error('An active bid already exists for this contractor and opportunity.');if(!$('wfSign').checked)throw Error('Confirm the sample signatory declaration.');const doc=files($('wfBidFile'))[0];if(!doc)throw Error('Choose a sample bid document.');const b={id:uid('REC'),supplierId:s.id,opportunityId:o.id,doc,status:'Submitted',reason:'',submittedAt:now()};state.bids.push(b);log('Sample bid submitted; file contents were not saved',b.id);save();$('wfBidFile').value='';$('wfSign').checked=false;$('wfReceipt').hidden=false;$('wfReceipt').textContent=`Demo receipt ${b.id} · ${b.submittedAt} · ${doc.name}. This is not a secure tender submission.`;notice(`Submission ${b.id} recorded.`)});
$('wfWithdraw').onclick=()=>run(()=>{const s=supplier(selected('wfBidSupplier')),o=opp(selected('wfBidOpportunity'));const b=state.bids.find(x=>x.supplierId===s?.id&&x.opportunityId===o?.id&&x.status==='Submitted');if(!b||new Date(o.close)<=new Date())throw Error('No active pre-close bid can be withdrawn.');b.status='Withdrawn';log('Submission withdrawn before close',b.id);save();notice(`${b.id} withdrawn.`)});
function decide(status){run(()=>{const b=bid(selected('wfEvalBid'));if(!b)throw Error('Choose a submission.');if(!['Submitted','Clarification requested'].includes(b.status))throw Error('This submission already has a final outcome.');if(status==='Awarded'&&new Date(opp(b.opportunityId).close)>new Date())throw Error('Award cannot be recorded before closing.');const reason=required(selected('wfDecisionReason'),'Decision reason');if(reason.length<15)throw Error('Enter an assessment reason of at least 15 characters.');b.status=status;b.reason=reason;if(status==='Awarded')state.contracts.push({id:uid('CTR'),bidId:b.id,supplierId:b.supplierId,stage:'Awarded',history:[]});log(`${status}: ${reason}`,b.id);save();notice(`${b.id}: ${status}.`)})}
$('wfAward').onclick=()=>decide('Awarded');$('wfClarify').onclick=()=>decide('Clarification requested');$('wfDecline').onclick=()=>decide('Unsuccessful');
$('wfAdvance').onclick=()=>run(()=>{const c=state.contracts.find(x=>x.id===selected('wfContract'));if(!c)throw Error('Choose a contract.');const stages=['Awarded','Contract signed','Delivery in progress','Work verified','Invoice reviewed','Closed out'];const next=selected('wfProgress');if(stages.indexOf(next)!==stages.indexOf(c.stage)+1)throw Error(`The next permitted stage is ${stages[stages.indexOf(c.stage)+1]||'none'}.`);const note=required(selected('wfProgressNote'),'Progress note');if(note.length<10)throw Error('Add a progress note of at least 10 characters.');c.stage=next;c.history.push({at:now(),stage:next,note});log(`${next}: ${note}`,c.id);save();notice(`${c.id} moved to ${next}.`)});
$('wfSeed').onclick=()=>{if(state.suppliers.length||state.opportunities.length){notice('Clear the browser demo before loading the sample journey.',true);return}const s={id:'SUP-SAMPLE',name:'Sample Tiling Co',csd:'MAAA0000000',category:'Tiling',area:'Blue Downs',doc:{name:'sample-compliance.pdf',size:0},version:1,status:'Awaiting review',reason:''};state.suppliers.push(s);state.opportunities.push({id:'RFQ-SAMPLE',method:'RFQ',title:'Sample tiling package',category:'Tiling',close:new Date(Date.now()+7*86400000).toISOString().slice(0,16),scope:'Illustrative tiling work only'});log('Synthetic journey loaded','SUP-SAMPLE');save();notice('Sample contractor and opportunity loaded. Review the contractor to continue.')};
$('wfReset').onclick=()=>{if(!confirm('Clear all synthetic records in this browser?'))return;state=initial();save();notice('Browser demo cleared.')};
const style=document.createElement('style');style.textContent='.wf-scroll{overflow-x:auto}.wf-scroll table{min-width:720px}.wf-scroll h4{margin:20px 0 6px}.wf-scroll h4:first-child{margin-top:0}#workflow .field input[type=checkbox]{width:auto;margin-right:7px}#wfNotice[hidden],#wfReceipt[hidden]{display:none}';document.head.append(style);
render();
})();
